#!/usr/bin/env bash
# Chek the file "school"
file="school"

if [ -e "$file" ]; then
    echo "${file} file exists"
    
    if [ -s "$file" ]; then
        echo "${file} file is not empty"
        
        if [ -f "$file" ]; then
            echo "${file} file is a regular file"
        fi
    else
        echo "${file} file is empty"
    fi
else
    echo "${file} file does not exist"
fi
